// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuF6Xa-q-zxf_3Q0_h67ILVddHhprIFys',
    appId: '1:1071203206871:web:0bb0c2400a2f1222a79292',
    messagingSenderId: '1071203206871',
    projectId: 'senai-8d2e4',
    authDomain: 'senai-8d2e4.firebaseapp.com',
    storageBucket: 'senai-8d2e4.appspot.com',
    measurementId: 'G-2YEYRVE24Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiNk0Et9C2Etv90OBtK2gcDDzRWb6go9Y',
    appId: '1:1071203206871:android:fcee38baa2dde26fa79292',
    messagingSenderId: '1071203206871',
    projectId: 'senai-8d2e4',
    storageBucket: 'senai-8d2e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAinXYX_xz-VMXJ3mnEEHIgr-4jD4j_5CM',
    appId: '1:1071203206871:ios:9e1a8099aa2ca992a79292',
    messagingSenderId: '1071203206871',
    projectId: 'senai-8d2e4',
    storageBucket: 'senai-8d2e4.appspot.com',
    iosBundleId: 'com.example.senaiProjeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAinXYX_xz-VMXJ3mnEEHIgr-4jD4j_5CM',
    appId: '1:1071203206871:ios:9e1a8099aa2ca992a79292',
    messagingSenderId: '1071203206871',
    projectId: 'senai-8d2e4',
    storageBucket: 'senai-8d2e4.appspot.com',
    iosBundleId: 'com.example.senaiProjeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuF6Xa-q-zxf_3Q0_h67ILVddHhprIFys',
    appId: '1:1071203206871:web:b46f3ec94ec0afc9a79292',
    messagingSenderId: '1071203206871',
    projectId: 'senai-8d2e4',
    authDomain: 'senai-8d2e4.firebaseapp.com',
    storageBucket: 'senai-8d2e4.appspot.com',
    measurementId: 'G-PN1QR577J9',
  );
}
